USE sucos_vendas;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAXIMO FROM tabela_de_produtos GROUP BY EMBALAGEM;

SELECT X.EMBALAGEM, X.PRECO_MAXIMO FROM
(SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAXIMO FROM tabela_de_produtos GROUP BY EMBALAGEM) X
WHERE X.PRECO_MAXIMO >= 10;

CREATE VIEW `VW_MAIORES_EMBALAGENS` AS 
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAXIMO FROM tabela_de_produtos GROUP BY EMBALAGEM;

SELECT X.EMBALAGEM, X.PRECO_MAXIMO FROM
vw_maiores_embalagens X WHERE X.PRECO_MAXIMO >= 10;

SELECT A.NOME_DO_PRODUTO, A.EMBALAGEM,A.PRECO_DE_LISTA, B.PRECO_MAXIMO
FROM tabela_de_produtos A INNER JOIN vw_maiores_embalagens B ON A.EMBALAGEM = B.EMBALAGEM;

SELECT A.NOME_DO_PRODUTO, A.EMBALAGEM,A.PRECO_DE_LISTA, B.PRECO_MAXIMO,
(A.PRECO_DE_LISTA / B.PRECO_MAXIMO) * 100 AS PERCENTUAL
FROM tabela_de_produtos A INNER JOIN vw_maiores_embalagens B ON A.EMBALAGEM = B.EMBALAGEM;

