USE sucos_vendas;

SELECT MAX(NUMERO) FROM notas_fiscais;

call p_inserir_venda('20190517', 20, 100);

SELECT A.NUMERO, SUM(B.QUANTIDADE * B.PRECO) AS FATURADO
FROM notas_fiscais A INNER JOIN ITENS_NOTAS_FISCAIS B
ON A.NUMERO = B.NUMERO WHERE A.DATA_VENDA = '20190517'
GROUP BY A.NUMERO;