USE sucos;
ALTER TABLE tbproduto ADD PRIMARY KEY(CODIGO_PRODUTO);
SELECT * FROM tbproduto;

INSERT INTO tbproduto (
CODIGO_PRODUTO,  NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES
('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml','Manga',5.18);
UPDATE tbproduto SET EMBALAGEM = 'GARRAFA'
WHERE CODIGO_PRODUTO = '1078680';
