SELECT * FROM tbcliente;

SELECT CPF, NOME FROM tbcliente LIMIT 5;

SELECT CPF AS CPF_CLIENTE, NOME AS NOME_CLIENT FROM tbcliente;

SELECT NOME, CPF, IDADE, SEXO, DATA_NASCIMENTO FROM tbcliente;

SELECT NOME, MATRICULA FROM tbvendedor;