USE sucos;
INSERT INTO tbvendedor(
MATRICULA, NOME, PERCENTUAL_COMISSAO) 
VALUES('00235', 'Márcio Almeida Silva', 0.08);
INSERT INTO tbvendedor(
MATRICULA, NOME, PERCENTUAL_COMISSAO) 
VALUES('00236', 'Cláudia Morais', 0.08);

SELECT * FROM tbvendedor;