SELECT 
JSON_UNQUOTE(JSON_EXTRACT(JSON, "$.Cpf")) AS CPF,
JSON_UNQUOTE(JSON_EXTRACT(JSON, "$.Primeiro_Nome")) AS PRIMEIRO_NOME,
JSON_UNQUOTE(JSON_EXTRACT(JSON, "$.Nome_Meio")) AS NOME_MEIO,
JSON_UNQUOTE(JSON_EXTRACT(JSON, "$.Ultimo_Nome")) AS ULTIMO_NOME,
TD.NOME_DEPARTAMENTO as NOME_DO_DEPARTAMENTO,
T1.NOME_DEPENDENTE, T1.SEXO, T1.PARENTESCO, T1.DATA_NASCIMENTO FROM tb_object_funcionario
CROSS JOIN
JSON_TABLE (JSON_EXTRACT (JSON, "$.Dependentes"), "$[*]"
COLUMNS (NOME_DEPENDENTE VARCHAR(30) PATH "$.Nome_Dependente",
SEXO VARCHAR(2) PATH "$.Sexo",
PARENTESCO VARCHAR(20) PATH "$.Parentesco",
DATA_NASCIMENTO DATETIME PATH "$.Data_Nascimento")) T1
INNER JOIN tb_departamento TD ON
TD.NUMERO_DEPARTAMENTO = JSON_UNQUOTE(JSON_EXTRACT(JSON, "$.Numero_Departamento")); 

SELECT JSON_EXTRACT(JSONVALUE, "$.Nome_Departamento"), JSON_EXTRACT(JSONVALUE, "$.Projeto[0].Nome_Projeto")
,  t2.CPF_FUNCIONARIO, t2.Horas FROM tb_object_departamento_projeto_trabalha_em
CROSS JOIN 
JSON_TABLE (JSON_EXTRACT(JSONVALUE, "$.Projeto[0].Horas_Trabalhadas"), "$[*]"
COLUMNS (CPF_FUNCIONARIO VARCHAR(10) PATH "$.Cpf_Funcionario", Horas integer PATH "$.Horas")) t2
UNION
SELECT JSON_EXTRACT(JSONVALUE, "$.Nome_Departamento"), JSON_EXTRACT(JSONVALUE, "$.Projeto[1].Nome_Projeto")
, t2.CPF_FUNCIONARIO, t2.Horas FROM tb_object_departamento_projeto_trabalha_em
CROSS JOIN 
JSON_TABLE (JSON_EXTRACT(JSONVALUE, "$.Projeto[1].Horas_Trabalhadas"), "$[*]"
COLUMNS (CPF_FUNCIONARIO VARCHAR(10) PATH "$.Cpf_Funcionario", Horas integer PATH "$.Horas")) t2;