USE vendas_sucos;

CREATE TABLE TAB_FATURAMENTO
(DATA_VENDA DATE,
TOTAL_VENDA FLOAT);

SELECT * FROM notas;

SELECT * FROM itens_notas;

INSERT INTO notas(NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES('0100', '2019-05-08', '1471156710', '235', 0.10);

INSERT INTO itens_notas(NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES('0100', '1000889', 100, 10);
INSERT INTO itens_notas(NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES('0100', '1002334', 100, 10);


INSERT INTO notas(NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES('0101', '2019-05-08', '1471156710', '235', 0.10);

INSERT INTO itens_notas(NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES('0101', '1000889', 100, 10);
INSERT INTO itens_notas(NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES('0101', '1002334', 100, 10);

INSERT INTO notas(NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES('0102', '2019-05-08', '1471156710', '235', 0.10);
INSERT INTO itens_notas(NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES('0102', '1000889', 100, 10);
INSERT INTO itens_notas(NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES('0102', '1002334', 100, 10);

DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO)  AS TOTAL_VENDA FROM NOTAS A 
INNER JOIN itens_notas B 
ON A.NUMERO = B.NUMERO
GROUP BY DATA_VENDA;

SELECT * FROM TAB_FATURAMENTO;

DELIMITER // 
CREATE TRIGGER TG_CALCULA_FATURAMENTO_INSERT AFTER INSERT ON itens_notas
FOR EACH ROW BEGIN
	DELETE FROM TAB_FATURAMENTO;
	INSERT INTO TAB_FATURAMENTO
	SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO)  AS TOTAL_VENDA FROM NOTAS A 
	INNER JOIN itens_notas B 
	ON A.NUMERO = B.NUMERO
	GROUP BY DATA_VENDA;
END//


DELIMITER //
CREATE TRIGGER TG_CLIENTES_IDADE_INSERT BEFORE INSERT ON CLIENTES
FOR EACH ROW
BEGIN
SET NEW.IDADE = timestampdiff(YEAR, NEW.DATA_NASCIMENTO, NOW());
END//
