USE vendas_sucos;

CREATE TABLE PRODUTOS
(CODIGO VARCHAR (10) NOT NULL,
DESCRITOR VARCHAR (100) NULL,
SABOR VARCHAR (50) NULL,
TAMANHO VARCHAR (50) NULL,
EMBALAGEM VARCHAR (50) NULL,
PRECO_LISTA FLOAT NULL,
PRIMARY KEY(CODIGO));

CREATE TABLE VENDEDORES
(MATRICULA VARCHAR (5) NOT NULL,
NOME VARCHAR (100) NULL,
BAIRRO VARCHAR (50) NULL,
COMISSAO FLOAT NULL,
DATA_ADMISSAO DATE NULL,
FERIAS BIT (1) NULL,
PRIMARY KEY(MATRICULA));


CREATE TABLE clientes (
  CPF VARCHAR (11) NOT NULL,
  NOME VARCHAR (100) NULL,
  ENDERECO VARCHAR (150) NULL,
  BAIRRO VARCHAR (50) NULL,
  CIDADE VARCHAR (50) NULL,
  ESTADO VARCHAR (45)  NULL,
  CEP  VARCHAR (8) NULL,
  DATA_NASCIMENTO DATE NULL,
  IDADE INT(11) NULL,
  SEXO VARCHAR (1)  NULL,
  LIMITE_CREDITO float NULL,
  VOLUME_COMPRA FLOAT NULL,
  PRIMEIRA_COMPRA BIT(1)  NULL,
  PRIMARY KEY (CPF));
  
 /* CREATE TABLE NOTAS
  (NUMERO VARCHAR (5) NOT NULL,
  DATA_VENDA DATE NULL,
  CPF VARCHAR (11) NOT NULL,
  MATRICULA VARCHAR (5) NOT NULL,
  IMPOSTO FLOAT NULL,
  PRIMARY KEY(NUMERO));*/

CREATE TABLE ITENS_NOTAS
(NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR (10) NOT NULL,
QUANTIDADE INT NULL,
PRECO FLOAT NULL,
PRIMARY KEY(NUMERO, CODIGO));

CREATE TABLE TABELA_DE_VENDAS
(NUMERO VARCHAR (5) NOT NULL,
DATA_VENDA DATE NULL,
CPF VARCHAR (11) NOT NULL,
MATRICULA VARCHAR (5) NOT NULL,
IMPOSTO FLOAT NULL,
PRIMARY KEY(NUMERO));


ALTER TABLE tabela_de_vendas ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY(CPF) REFERENCES clientes (CPF);

ALTER TABLE tabela_de_vendas ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY(MATRICULA) REFERENCES vendedores (MATRICULA);

ALTER TABLE itens_notas ADD CONSTRAINT FK_NOTAS
FOREIGN KEY (NUMERO) REFERENCES tabela_de_vendas (NUMERO);

ALTER TABLE itens_notas ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO) REFERENCES PRODUTOS (CODIGO);
